version: '3'
services:
  # Application Dockerfile is in the same folder which is .
  app:
    build: .

  # db is in the db folder
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always